# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run update.py # 2) update.py 실행
      run: |
        python update.py
    - name: Commit changes # 3) 추가된 파일 commit
      run: |
        git config --global user.name 'junghunim01' # 유저명
        git config --global user.email '191111@jnu.ac.kr' # 유저 이메일
        git add -A
        git commit -am "auto update README.md" # 커밋 메시지
    - name: Push changes # 4) 메인에 푸시
      run: |
        git push
