name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies # 1) 스크립트에 필요한 dependency 설치
      run: |
        python -m pip install --upgrade pip
        pip install python-leetcode 
    - name: Run update.py # 2) update.py 실행
      run: |
        python update.py
    - name: Commit changes # 3) 추가된 파일 commit
      run: |
        git config --global user.name 'junghunim07' # 유저명
        git config --global user.email '191111@jnu.ac.kr' # 유저 이메일
        git add -A
        git commit -am "auto update README.md" # 커밋 메시지
    - name: Push changes # 4) 메인에 푸시
      run: |
        git remote set-url origin https://x-access-token:${{ secrets.ACTIONS_TOKEN }}@github.com/junghunim07/Algorithm.git
        git push origin HEAD:main
      env:
        ACTIONS_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
